"""Reads real solved-field output from a completed chtMultiRegionSimpleFoam
run and samples it onto arbitrary query points.

Nearest-cell-centre sampling, not interpolation: for each query point we find
the closest OpenFOAM cell centre (via a KD-tree) in the requested region and
take that cell's value. This is deliberate, not a shortcut — the frontend's
displayed surface is generated by a completely different algorithm (surface
nets, in-browser) than the one OpenFOAM's own mesh boundary came from
(marching cubes -> STL -> snappyHexMesh, server-side), at a different voxel
resolution, so there is no shared vertex indexing to exploit. See
backend/README.md for the "three different triangulations of the same
implicit field" note. Cell centres are obtained via OpenFOAM's own
`postProcess -func writeCellCentres`, not recomputed by hand from mesh
points/faces.

Field-file parsing note: vector rows are themselves parenthesised
("(x y z)"), so scanning for the list's closing ")" naively finds the first
row's parenthesis, not the list's — this bit exactly once during development
and is why the parser below counts exactly N data lines from the header
instead of searching for a closing bracket.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Literal

import numpy as np

from .foam_case import run

RegionKey = Literal["solid", "hot", "cold"]
FieldName = Literal["temperature", "velocity", "pressure"]

_FIELD_FILE = {"temperature": "T", "velocity": "U", "pressure": "p"}
# The solid region has no momentum/pressure equation — its `p` file exists
# only because chtMultiRegionSimpleFoam requires the field to be present,
# and stays bit-identical to its uniform initial value through the whole
# solve (verified empirically, not assumed). Only T is real there.
_SOLID_FIELDS = {"temperature"}

_HEADER_RE = re.compile(r"internalField\s+nonuniform\s+List<(scalar|vector)>\s*\n(\d+)\s*\n\(", re.MULTILINE)
_UNIFORM_RE = re.compile(r"internalField\s+uniform\s+([\-\d.eE]+)")


class FieldUnavailable(RuntimeError):
    pass


def latest_time_dir(case_dir: Path) -> str:
    """The highest-numbered time directory actually on disk. controlDict's
    purgeWrite keeps only the last couple of write intervals, so this is not
    predictable from maxIterations alone — it has to be discovered."""
    times = [p.name for p in case_dir.iterdir() if p.is_dir() and re.fullmatch(r"\d+(\.\d+)?", p.name) and p.name != "0"]
    if not times:
        raise FieldUnavailable("no solved time directory found in this case – run a solve first")
    return max(times, key=float)


def _parse_internal_field(text: str) -> np.ndarray:
    m = _HEADER_RE.search(text)
    if not m:
        um = _UNIFORM_RE.search(text)
        if um:
            return np.array([float(um.group(1))], dtype=np.float64)
        raise FieldUnavailable("could not parse internalField – unrecognised OpenFOAM field file format")

    kind, n = m.group(1), int(m.group(2))
    lines = text[m.end():].split("\n")
    while lines and lines[0].strip() == "":
        lines.pop(0)
    data_lines = lines[:n]
    if len(data_lines) != n:
        raise FieldUnavailable(f"expected {n} data rows, found {len(data_lines)}")

    if kind == "scalar":
        return np.array([float(row) for row in data_lines], dtype=np.float64)
    return np.array([[float(v) for v in row.strip("()").split()] for row in data_lines], dtype=np.float64)


def write_cell_centres(case_dir: Path, region: RegionKey, time: str) -> None:
    result = run(["postProcess", "-func", "writeCellCentres", "-region", region, "-time", time], case_dir)
    if result.returncode != 0:
        raise FieldUnavailable(f"writeCellCentres failed:\n{result.stdout[-2000:]}\n{result.stderr[-1000:]}")


def read_cell_centres(case_dir: Path, region: RegionKey, time: str) -> np.ndarray:
    path = case_dir / time / region / "C"
    if not path.exists():
        write_cell_centres(case_dir, region, time)
    if not path.exists():
        raise FieldUnavailable(f"{path} still missing after writeCellCentres")
    return _parse_internal_field(path.read_text())


def read_field(case_dir: Path, region: RegionKey, time: str, field: FieldName) -> np.ndarray:
    if region == "solid" and field not in _SOLID_FIELDS:
        raise FieldUnavailable(f"{field} has no real solved data in the solid region – it has no momentum equation there")
    path = case_dir / time / region / _FIELD_FILE[field]
    if not path.exists():
        raise FieldUnavailable(f"{path} not found – was this region actually solved?")
    values = _parse_internal_field(path.read_text())
    if field == "velocity":
        values = np.linalg.norm(values, axis=1)
    return values


def sample_field(case_dir: Path, region: RegionKey, field: FieldName, points_m: np.ndarray) -> tuple[np.ndarray, float, float]:
    """points_m: (N, 3) query points in metres. Returns (values, min, max) —
    one value per query point, from its nearest OpenFOAM cell centre."""
    time = latest_time_dir(case_dir)
    values = read_field(case_dir, region, time, field)

    if len(values) == 1:
        sampled = np.full(len(points_m), values[0], dtype=np.float64)
        return sampled, float(values[0]), float(values[0])

    centres = read_cell_centres(case_dir, region, time)
    if len(centres) != len(values):
        raise FieldUnavailable("cell-centre / field cell-count mismatch – mesh may have changed since the solve")

    from scipy.spatial import cKDTree

    tree = cKDTree(centres)
    _, idx = tree.query(points_m)
    sampled = values[idx]
    return sampled, float(sampled.min()), float(sampled.max())
